version: 2.0

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache: # 依存関係キャッシュを復元する特別なステップ
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
        name: install
        command: yarn install
      - save_cache: # 依存関係キャッシュを保存する特別なステップ
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache: # 依存関係キャッシュを復元する特別なステップ
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
        name: install
        command: yarn install
      - run: # テストを実行
        name: test
        command: yarn test
  deploy:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache: # 依存関係キャッシュを復元する特別なステップ
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
        name: install
        command: yarn install
      - run:
        name: release
        command: yarn run semantic-release || true

workflows:
  version: 2
  release:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
